name: acrcloud_rest
description: A Dart http client for the ACRCloud service.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

dependencies:
  crypto: ^3.0.2
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_serializable: ^6.5.4
